/*
* AUTOGENERATED FILE
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))=
        "****************"  // placeholder for beggining
        "20260615T201836"   // DateTime using ISO-8601 format
        " "                 // alignment
        "f29a5135"          // STLIB commit
        "--------"          // ADJ commit
        "a704b90f"          // Board commit
        // the '=' is used for unparsing
        ;
}