/*
* AUTOGENERATED FILE
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))=
        "****************"  // placeholder for beggining
        "20260418T125503"   // DateTime using ISO-8601 format
        " "                 // alignment
        "f8c628fa"          // STLIB commit
        "--------"          // ADJ commit
        "84e04f59"          // Board commit
        // the '=' is used for unparsing
        ;
}