#pragma once
#include "ST-LIB.hpp"

/*Data packets for LV-BMS
-AUTOGENERATED CODE, DO NOT MODIFY-*/
class DataPackets{
public:
    enum class State : uint8_t
    {
        CONNECTING = 0,
        OPERATIONAL = 1,
        FAULT = 2,
    };
    

    static void Battery_Voltages_init(uint32_t &cell_1, uint32_t &cell_2, uint32_t &cell_3, uint32_t &cell_4, uint32_t &cell_5, uint32_t &cell_6, uint32_t &voltage_min, uint32_t &voltage_max, float &total_voltage)
    {
        Battery_Voltages_packet = new HeapPacket(static_cast<uint16_t>(777), &cell_1, &cell_2, &cell_3, &cell_4, &cell_5, &cell_6, &voltage_min, &voltage_max, &total_voltage);
    }

    static void Battery_Temperatures_init(float &temperature_1)
    {
        Battery_Temperatures_packet = new HeapPacket(static_cast<uint16_t>(778), &temperature_1);
    }

    static void State_of_Charge_init(float &SOC)
    {
        State_of_Charge_packet = new HeapPacket(static_cast<uint16_t>(779), &SOC);
    }

    static void Battery_Current_init(float &current)
    {
        Battery_Current_packet = new HeapPacket(static_cast<uint16_t>(780), &current);
    }

    static void Current_State_init(State &State)
    {
        Current_State_packet = new HeapPacket(static_cast<uint16_t>(781), &State);
    }

    public:
    inline static HeapPacket *Battery_Voltages_packet{nullptr};
    inline static HeapPacket *Battery_Temperatures_packet{nullptr};
    inline static HeapPacket *State_of_Charge_packet{nullptr};
    inline static HeapPacket *Battery_Current_packet{nullptr};
    inline static HeapPacket *Current_State_packet{nullptr};
    
    inline static DatagramSocket *control_station_udp{nullptr};
    

    static void start()
    {
        if (Battery_Voltages_packet == nullptr) {
            PANIC("Packet Battery_Voltages not initialized");
        }
        if (Battery_Temperatures_packet == nullptr) {
            PANIC("Packet Battery_Temperatures not initialized");
        }
        if (State_of_Charge_packet == nullptr) {
            PANIC("Packet State_of_Charge not initialized");
        }
        if (Battery_Current_packet == nullptr) {
            PANIC("Packet Battery_Current not initialized");
        }
        if (Current_State_packet == nullptr) {
            PANIC("Packet Current_State not initialized");
        }
        

        control_station_udp = new DatagramSocket("192.168.1.11",50400,"192.168.0.9",50400);
        
        Scheduler::register_task(16670, +[](){
            DataPackets::control_station_udp->send_packet(*DataPackets::Battery_Voltages_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::Battery_Temperatures_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::State_of_Charge_packet);
            DataPackets::control_station_udp->send_packet(*DataPackets::Battery_Current_packet);
            });
        Scheduler::register_task(100000, +[](){
            DataPackets::control_station_udp->send_packet(*DataPackets::Current_State_packet);
            });
    }



};