#pragma once
#include "ST-LIB.hpp"

/*Order packets for LV-BMS 
-AUTOGENERATED CODE, DO NOT MODIFY- */


class OrderPackets{
public:
    

    inline static bool Turn_on_PFM_flag{false};
    inline static bool Turn_off_PFM_flag{false};
    inline static bool Set_PFM_Frequency_flag{false};
    inline static bool Set_PFM_Dead_Time_flag{false};
    

    OrderPackets() = default;

    inline static HeapOrder *Turn_on_PFM{nullptr};
    inline static HeapOrder *Turn_off_PFM{nullptr};
    inline static HeapOrder *Set_PFM_Frequency{nullptr};
    inline static HeapOrder *Set_PFM_Dead_Time{nullptr};
    
    
    static void Turn_on_PFM_init()
    {
        Turn_on_PFM = new HeapOrder(502, &Turn_on_PFM_cb);
    }
    static void Turn_off_PFM_init()
    {
        Turn_off_PFM = new HeapOrder(503, &Turn_off_PFM_cb);
    }
    static void Set_PFM_Frequency_init(uint32_t &frequency)
    {
        Set_PFM_Frequency = new HeapOrder(504, &Set_PFM_Frequency_cb, &frequency);
    }
    static void Set_PFM_Dead_Time_init(uint32_t &dead_time)
    {
        Set_PFM_Dead_Time = new HeapOrder(505, &Set_PFM_Dead_Time_cb, &dead_time);
    }
    

private:
    static void Turn_on_PFM_cb()
    {
        Turn_on_PFM_flag = true;
    }
    static void Turn_off_PFM_cb()
    {
        Turn_off_PFM_flag = true;
    }
    static void Set_PFM_Frequency_cb()
    {
        Set_PFM_Frequency_flag = true;
    }
    static void Set_PFM_Dead_Time_cb()
    {
        Set_PFM_Dead_Time_flag = true;
    }
    
};