#pragma once
#include "ST-LIB.hpp"

/*Order packets for LV-BMS 
-AUTOGENERATED CODE, DO NOT MODIFY- */


class OrderPackets{
public:
    

    inline static bool Brake_flag{false};
    

    OrderPackets() = default;

    inline static HeapOrder *Brake_order{nullptr};
    
    
    static void Brake_init()
    {
        Brake_order = new HeapOrder(43, &Brake_cb);
    }
    

private:
    static void Brake_cb()
    {
        Brake_flag = true;
    }
    
};