#pragma once
#include "ST-LIB.hpp"

/*Order packets for LV-BMS
-AUTOGENERATED CODE, DO NOT MODIFY- */

class OrderPackets{
public:
    

    inline static bool Brake_flag{false};
    

    OrderPackets() = default;

#if STLIB_ETH
    inline static HeapOrder *Brake_order{nullptr};
#else
    inline static void *Brake_order{nullptr};
#endif


    static void Brake_init()
    {
#if STLIB_ETH
        Brake_order = new HeapOrder(43, &Brake_cb);
#endif
    }
    

#if STLIB_ETH
    inline static ServerSocket *control_station_tcp{nullptr};
#else
    inline static void *control_station_tcp{nullptr};
#endif

    static void start()
    {
        if (Brake_order == nullptr) {
            FAULT("Order Brake not initialized");
        }

#if STLIB_ETH
        control_station_tcp = new ServerSocket("192.168.1.11",50500);
#endif        
    }

private:
    static void Brake_cb()
    {
        Brake_flag = true;
    }
    
};